services:
  db:
    image: postgres:15-alpine
    container_name: wbjj_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wbjj_dev
      POSTGRES_USER: wbjj_user
      POSTGRES_PASSWORD: wbjj_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wbjj_user -d wbjj_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: wbjj_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis_pass
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Opcional: Adminer para gerenciar banco via web
  adminer:
    image: adminer:latest
    container_name: wbjj_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
