# Generated by Django 4.2.23 on 2025-07-09 18:59

import uuid

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain_url",
                    models.CharField(
                        help_text="Domínio do tenant (ex: academia-teste.wbjj.com)",
                        max_length=253,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nome da academia", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug único para subdomínio (ex: gracie-barra)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email principal da academia", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Telefone da academia",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")
                        ],
                    ),
                ),
                ("address", models.TextField(help_text="Endereço completo")),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=10)),
                ("country", models.CharField(default="Brasil", max_length=50)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Cor primária em hex (ex: #3B82F6)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator("^#[0-9A-Fa-f]{6}$")
                        ],
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#1E40AF",
                        help_text="Cor secundária em hex",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator("^#[0-9A-Fa-f]{6}$")
                        ],
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=150.0,
                        help_text="Mensalidade padrão",
                        max_digits=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Sao_Paulo",
                        help_text="Timezone da academia",
                        max_length=50,
                    ),
                ),
                ("founded_date", models.DateField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Academia ativa"),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="tenants_ten_slug_63daca_idx"),
                    models.Index(
                        fields=["schema_name"], name="tenants_ten_schema__df93bb_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="tenants_ten_is_acti_8f654a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
