# Generated by Django 4.2.23 on 2025-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("gi", "Gi (Kimono)"),
                    ("no_gi", "No-Gi"),
                    ("competition", "Competição"),
                    ("kids", "Infantil"),
                    ("fundamentals", "Fundamentos"),
                    ("advanced", "Avançado"),
                    ("open_mat", "Treino Livre"),
                    ("seminar", "Seminário"),
                    ("regular", "Regular"),
                ],
                default="regular",
                help_text="Tipo de aula",
                max_length=50,
            ),
        ),
    ]
