"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-t@k7#yb5u=)dd4gpb%p*%5^3-&m37xko4g6k8*7pws*bm(l!y&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",  # Django Unfold deve vir antes do admin
    "unfold.contrib.filters",  # Filtros aprimorados
    "unfold.contrib.forms",  # Formulários aprimorados
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local apps
    "apps.core",
    "apps.tenants",
    "apps.authentication",
    "apps.students",
    "apps.payments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.core.middleware.PermissionsPolicyMiddleware",  # Middleware para Permissions Policy
    "apps.core.middleware.SecurityHeadersMiddleware",  # Middleware para cabeçalhos de segurança
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Configurações adicionais do admin Django
ADMIN_SITE_HEADER = "Zenith Jiu Jitsu - Administração"
ADMIN_SITE_TITLE = "Zenith JJ Admin"
ADMIN_INDEX_TITLE = "Painel Administrativo"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Custom User Model
AUTH_USER_MODEL = "authentication.User"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "pt-BR"

TIME_ZONE = "America/Cuiaba"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR.parent / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "SAMEORIGIN"  # Mudando para SAMEORIGIN para permitir iframe no admin

# Django Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "Zenith Jiu Jitsu",
    "SITE_HEADER": "Zenith JJ Admin",
    "SITE_URL": "/",
    "SITE_LOGO": "/static/images/logo.png",
    "SITE_ICON": {
        "light": "/static/images/logo.png",
        "dark": "/static/images/logo.png",
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: request.build_absolute_uri(
                "/static/images/logo.png"
            ),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": None,
    "COLORS": {
        "primary": {
            "50": "255 255 240",  # Amarelo muito claro
            "100": "254 249 195",  # Amarelo claro
            "200": "254 240 138",  # Amarelo suave
            "300": "253 224 71",  # Amarelo médio
            "400": "250 204 21",  # Amarelo vibrante
            "500": "234 179 8",  # Amarelo principal (como no logo)
            "600": "202 138 4",  # Amarelo escuro
            "700": "161 98 7",  # Amarelo mais escuro
            "800": "133 77 14",  # Amarelo muito escuro
            "900": "113 63 18",  # Amarelo quase laranja
            "950": "66 32 6",  # Amarelo mais escuro
        }
    },
    "THEME": "light",  # Define tema padrão como claro para destacar as cores amarelo/azul
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        # Removendo navegação customizada temporariamente para resolver problema
        # "navigation": [...]
    },
}
